import enum


class EfiFirmwareFileType(enum.Enum):
    """
    Enum for UEFI file type values
    # https://github.com/tianocore/edk2/blob/4c8144dd665619731b6c3c19f4f1ae664b69fa4b/BaseTools/Source/C/Include/Common/PiFirmwareFile.h#L33
    """
    EFI_FV_FILETYPE_ALL = 0x00
    EFI_FV_FILETYPE_RAW = 0x01
    EFI_FV_FILETYPE_FREEFORM = 0x02
    EFI_FV_FILETYPE_SECURITY_CORE = 0x03
    EFI_FV_FILETYPE_PEI_CORE = 0x04
    EFI_FV_FILETYPE_DXE_CORE = 0x05
    EFI_FV_FILETYPE_PEIM = 0x06
    EFI_FV_FILETYPE_DRIVER = 0x07
    EFI_FV_FILETYPE_COMBINED_PEIM_DRIVER = 0x08
    EFI_FV_FILETYPE_APPLICATION = 0x09
    EFI_FV_FILETYPE_MM = 0x0A
    EFI_FV_FILETYPE_FIRMWARE_VOLUME_IMAGE = 0x0B
    EFI_FV_FILETYPE_COMBINED_MM_DXE = 0x0C
    EFI_FV_FILETYPE_MM_CORE = 0x0D
    EFI_FV_FILETYPE_MM_STANDALONE = 0x0E
    EFI_FV_FILETYPE_MM_CORE_STANDALONE = 0x0F
    EFI_FV_FILETYPE_OEM_MIN = 0xC0
    EFI_FV_FILETYPE_OEM_MAX = 0xDF
    EFI_FV_FILETYPE_DEBUG_MIN = 0xE0
    EFI_FV_FILETYPE_DEBUG_MAX = 0xEF
    EFI_FV_FILETYPE_PAD = 0xF0
    EFI_FV_FILETYPE_FFS_MIN = 0xF0
    EFI_FV_FILETYPE_FFS_MAX = 0xFF
